### ISSUE TITLE
Can I query the postgres database directly from a sql client? Any examples of that?

### ISSUE THREAD

**Issue by adrianog** [mwielgoszewski/doorman#100]
Thank you for the effort you put into this, looks neat.

**Comment by mwielgoszewski** [comment]
@adrianog Sure! Using a psql client, just connect to the postgres database Doorman logs results to and construct queries like:

```
SELECT node_id, columns ->> 'hostname', columns ->> 'hardware_serial' FROM result_log WHERE name LIKE '%system_info%';
```

or:

```
SELECT n.host_identifier, n.is_active, n.last_ip, n.last_checkin, r.columns ->> 'hostname', r.columns ->> 'hardware_serial' FROM result_log r INNER JOIN node n ON r.node_id = n.id WHERE r.name LIKE '%system_info%';
           host_identifier            | is_active |  last_ip  |        last_checkin        | ?column?  |   ?column?   
--------------------------------------+-----------+-----------+----------------------------+-----------+--------------
..snip..
```

**Comment by adrianog** [comment]
ok I guess I should have played a bit first. Looks intuitive. 
This indirectly satisfies my original quest of finding a jdbc interface to osquery. That way I can use all my existing sql clients / build ad hoc reports with anything accepting a jdbc source, including Excel.
