### ISSUE TITLE
CSRF token not being set 

### ISSUE THREAD

**Issue by Oneiroi** [mwielgoszewski/doorman#102]
Quick bug report:

When trying to add a pack an error occurs:

![image](https://user-images.githubusercontent.com/478678/27088694-4e67e2ce-5050-11e7-996a-01fe4982c1ed.png)

This also occurs if you try to add a new rule and as noted in #101 this intermittently occurs when adding a query also.

**Comment by mwielgoszewski** [comment]
CSRF token errors occur when you're on http:// site, your browser never remembers the cookie that's set because it's marked secure.
