### ISSUE TITLE
After ran "python manage.py db upgrade", I had to manually fix on line 72 this file /opt/doorman-master/migrations/versions/30e928796227_.py

### ISSUE THREAD

**Issue by flaviod** [mwielgoszewski/doorman#105]
Hi Marcin,

I tried to link with you on Linkedin. I'd love to connect with you.

Anyways, I am "playing" with your tool.. pretty good job and I liked. Since I am new to Flask I ahd some rocks on my way. See bellow:

bash-4.2$ python manage.py db migrate
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'distributed_query'
INFO  [alembic.autogenerate.compare] Detected added table 'file_path'
INFO  [alembic.autogenerate.compare] Detected added table 'node'
INFO  [alembic.autogenerate.compare] Detected added table 'pack'
INFO  [alembic.autogenerate.compare] Detected added table 'query'
INFO  [alembic.autogenerate.compare] Detected added table 'rule'
INFO  [alembic.autogenerate.compare] Detected added table 'tag'
INFO  [alembic.autogenerate.compare] Detected added table 'user'
INFO  [alembic.autogenerate.compare] Detected added table 'distributed_query_task'
INFO  [alembic.autogenerate.compare] Detected added table 'file_path_tags'
INFO  [alembic.autogenerate.compare] Detected added table 'node_tags'
INFO  [alembic.autogenerate.compare] Detected added table 'pack_tags'
INFO  [alembic.autogenerate.compare] Detected added table 'query_packs'
INFO  [alembic.autogenerate.compare] Detected added table 'query_tags'
INFO  [alembic.autogenerate.compare] Detected added table 'result_log'
INFO  [alembic.autogenerate.compare] Detected added table 'status_log'
INFO  [alembic.autogenerate.compare] Detected added table 'distributed_query_result'
  Generating /opt/doorman-master/migrations/versions/30e928796227_.py ... done
bash-4.2$ cp /opt/doorman-master/migrations/versions/30e928796227_.py /opt/doorman-master/migrations/versions/30e928796227_.py.bak
bash-4.2$ vi /opt/doorman-master/migrations/versions/30e928796227_.py
bash-4.2$ vi +72 /opt/doorman-master/migrations/versions/30e928796227_.py
bash-4.2$ python manage.py db upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 30e928796227, empty message
Traceback (most recent call last):
  File "manage.py", line 101, in <module>
    manager.run()
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_migrate/__init__.py", line 235, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 87, in <module>
    run_migrations_online()
  File "migrations/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/opt/doorman-master/migrations/versions/30e928796227_.py", line 72, in upgrade
    sa.Column('alerters', postgresql.ARRAY(String), nullable=False),
NameError: global name 'String' is not defined

So, to "fix it" (I am not a python nor Flask developer), I just edited that line 72 from

sa.Column('alerters', postgresql.ARRAY(String()), nullable=False),

to

sa.Column('alerters', postgresql.ARRAY(sa.String()), nullable=False), 

So, in this way I was able to start Doorman. Great!

Now, I am trying to figure out, if during the enroolment, I would be able to have the workload (the client) to send a **tag**. I know, that doorman you can have a default tab, but it ould be great if the client could send this information during enrollmanet. What do you think?

Best Regards,

Flavio.

**Comment by mwielgoszewski** [comment]
Hi @flaviod, you should not have to run `python manage.py db migrate` at all. That's done by developers when generating new db migration files.

You only need to run `python manage.py db upgrade`. 

Regarding your second request, I don't think osquery has this capability... unless you do what the Heroku Windmill project does and overloads the enroll secret with some colon separated values.
