### ISSUE TITLE
enroll issue

### ISSUE THREAD

**Issue by rubenrodr-versia** [mwielgoszewski/doorman#111]
Hi,

We have deployed a doorman test on host 10.191.29.208 but when trying to enroll a node we get an error launching osqueryd.
We have generated the cert as follows:

> openssl genrsa -out /opt/doorman/private.key 2048
> openssl req -x509 -new -nodes -key /opt/doorman/private.key -days 365 -out /opt/doorman/certificate.crt -subj /C=US/O=doorman/CN=10.191.29.208

And this is the config file for nginx:

> server {
>   listen 443;

>   ssl on;
>   ssl_certificate /opt/doorman/certificate.crt;
>   ssl_certificate_key /opt/doorman/private.key;

>   location / {
>     proxy_pass https://127.0.0.1:5000;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection 'upgrade';
>     proxy_set_header Host $host;
>     proxy_cache_bypass $http_upgrade;
>   }
> }

We use the following osqueryd.flags:
> --pidfile=/tmp/osquery.pid
> --host_identifier=hostname
> --database_path=/tmp/osquery.db
> --config_plugin=tls
> --config_tls_endpoint=/config
> --config_tls_refresh=10
> --config_tls_max_attempts=3
> --enroll_tls_endpoint=/enroll
> --enroll_secret_env=ENROLL_SECRET
> --disable_distributed=false
> --distributed_plugin=tls
> --distributed_interval=10
> --distributed_tls_max_attempts=3
> --distributed_tls_read_endpoint=/distributed/read
> --distributed_tls_write_endpoint=/distributed/write
> --logger_plugin=tls
> --logger_tls_endpoint=/log
> --logger_tls_period=5
> --tls_hostname=10.191.29.208
> --tls_server_certs=/etc/osquery/certificate.crt
> --disable_enrollment=false
> --log_result_events=false
> --pack_delimiter=/
> --utc
> --verbose
> --tls_dump=true

and these are the error messages:
> I0810 16:24:55.620905  8203 init.cpp:392] osquery initialized [version=2.6.0]
> I0810 16:24:55.641551  8203 system.cpp:321] Found stale process for osqueryd (7869)
> I0810 16:24:55.641651  8203 system.cpp:356] Writing osqueryd pid (8203) to /tmp/osquery.pid
> I0810 16:24:55.641733  8203 extensions.cpp:286] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
> I0810 16:24:55.642452  8204 watcher.cpp:501] osqueryd watcher (8203) executing worker (8205)
> I0810 16:24:55.649924  8205 init.cpp:389] osquery worker initialized [watcher=8203]
> I0810 16:24:55.650090  8205 rocksdb.cpp:214] Opening RocksDB handle: /tmp/osquery.db
> I0810 16:24:55.939425  8212 interface.cpp:326] Extension manager service starting: /var/osquery/osquery.em
> I0810 16:24:55.939573  8205 tls_enroll.cpp:68] TLSEnrollPlugin requesting a node enroll key from: https://10.191.29.208/enroll
> I0810 16:24:55.939901  8205 tls.cpp:205] TLS/HTTPS POST request to URI: https://10.191.29.208/enroll
> {"enroll_secret":"secret","host_identifier":"rubenrodr","platform_type":"9"}
> ....
> E0810 16:25:27.536238  8205 init.cpp:568] Cannot activate tls logger plugin: No node key, TLS logging disabled.

Thanks in advance.
Best regards.

**Comment by mwielgoszewski** [comment]
Is your `DOORMAN_ENROLL_SECRET` in your doorman configuration set properly?

**Comment by rubenrodr-versia** [comment]
Hi,
The issue is resolved, the client was a windows host and the osquery.flags file format was unix insted of dos.
Thanks.
