### ISSUE TITLE
error adding user manage.py

### ISSUE THREAD

**Issue by rubenrodr-versia** [mwielgoszewski/doorman#127]
Hi Marcin,

Im trying to configure doorman authentication, but when i try to generate admin user with manage.py i get the following error:

![image](https://user-images.githubusercontent.com/24841626/29868943-31eeafa6-8d81-11e7-8069-0dc4ee5dfd5f.png)

Thanks.
Best regards.

**Comment by mwielgoszewski** [comment]
You’re running into a postgres user error here. Since you’re running manage.py as root, it tries to connect to postgres as root. Try sudo’ing to doorman or postgres user.

Confirmed in osquery Slack this fixes the problem.
