### ISSUE TITLE
Windows serial number -1

### ISSUE THREAD

**Issue by rubenrodr-versia** [mwielgoszewski/doorman#130]
The serial of windows clients enrolled to doorman are being displayed with value -1:

![image](https://user-images.githubusercontent.com/24841626/30151512-0c443c1e-93b0-11e7-9f43-101e01428b57.png)

The linux hosts serials are taken from system_info.uuid 
![image](https://user-images.githubusercontent.com/24841626/30151596-5bd6efba-93b0-11e7-9bb1-9304ad520853.png)

if i run the query on w10 host:
![image](https://user-images.githubusercontent.com/24841626/30151536-21e959dc-93b0-11e7-8cc6-da976d262461.png)

Thanks.

**Comment by mwielgoszewski** [comment]
Hey @rubenrodr-versia, what is your `DOORMAN_CAPTURE_NODE_INFO` configuration value set to?

**Comment by rubenrodr-versia** [comment]
Hi Marcin,

These are the configured values:

![image](https://user-images.githubusercontent.com/24841626/30168587-248493c0-93ea-11e7-882e-34d5c750c812.png)

Thanks.
Best regards.

**Comment by rubenrodr-versia** [comment]
Hi Marcin,

I noticed that on physical laptop (ubuntu 17.04):
![image](https://user-images.githubusercontent.com/24841626/30168761-a1252d7c-93ea-11e7-9397-3b57122d470f.png)

and vm running on nutanix (ubuntu 16.04):
![image](https://user-images.githubusercontent.com/24841626/30168807-bfb5fa14-93ea-11e7-8ec1-3788defbf466.png)

Thanks.

**Comment by mwielgoszewski** [comment]
Your sql query needs to read a column named `hardware_serial`. Your second queries you just posted (`select uuid, hadware_serial from system_info;`) achieves this.

**Comment by rubenrodr-versia** [comment]
I tought that the field doorman was getting the info from was uuid, but is hardware_serial, which on windows is -1:
![image](https://user-images.githubusercontent.com/24841626/30168961-3f5b749c-93eb-11e7-9954-c1ceeb417a81.png)

 As the past post uuid=hardware_serial on nutanix vm but not on physical.

**Comment by mwielgoszewski** [comment]
Closing this issue, as this is now an osquery/virtual machine thing.
