### ISSUE TITLE
PostgeSQL 10 needs psycopg2 >= 2.7.0

### ISSUE THREAD

**Issue by NickTaylor-** [mwielgoszewski/doorman#138]
Related psycopg2 bug: https://github.com/psycopg/psycopg2/issues/489

With PostgreSQL versions 10 or later, the version parsing that psycopg2 does no longer works due to a new naming schema. To resolve this, either the version of psycopg2 needs to be updated, or the version of PosgreSQL needs to be specified to be lower than 10.

Running into other build issues at the moment, so I am unable to confirm whether or not there are any issues with an upgrade to psycopg2 (the best route), but will report back if/when I get it working.

**Comment by erichs** [comment]
I'm also seeing this: `Error: could not determine PostgreSQL version from '10.1'`

**Comment by erichs** [comment]
@NickTaylor- were you able to produce a working build?

**Comment by NickTaylor-** [comment]
I believe I was able to get it running by just changing this line in requirements.txt

`psycopg2==2.6.1`
to
`psycopg2==2.7.0`

**Comment by mwielgoszewski** [comment]
Fixed in #139.
