### ISSUE TITLE
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  Ident authentication failed for user "root"

### ISSUE THREAD

**Issue by PremaPrems** [mwielgoszewski/doorman#141]
My Pg_hba.conf file is 
# PostgreSQL Client Authentication Configuration File
# ===================================================
#
# Database administrative login by Unix domain socket
local   all             postgres                                trust
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust

Still am not able to do python manage.py db upgrade.

**Comment by lijianfang** [comment]
same issus, had you done?
