### ISSUE TITLE
Code Climate integration

### ISSUE THREAD

**Issue by dguido** [mwielgoszewski/doorman#35]
Code Climate is free for open source programs, so why not? They only have 3 engines that support Python. I think they can also track test coverage.

* https://docs.codeclimate.com/v1.0/docs/radon
* https://docs.codeclimate.com/v1.0/docs/pep8
* https://docs.codeclimate.com/v1.0/docs/duplication

**Comment by dguido** [comment]
Sample config file from one of our projects:
https://github.com/trailofbits/protofuzz/blob/master/.codeclimate.yml

**Comment by mwielgoszewski** [comment]
I'm not sure why Code Climate needs access to all of the following, seems a bit excessive:

![image](https://cloud.githubusercontent.com/assets/359029/15399181/a9c61fb6-1db4-11e6-9e8f-e71044bb9818.png)

**Comment by dguido** [comment]
Looks like you don't have to link it at all for OSS apps. Just put a well-formed .codeclimate.yml file into the root directory and then add the repo to the dashboard on codeclimate.com.

"You do not have to link your Code Climate user to your GitHub user in order to add a GitHub-hosted open source project to Code Climate. To do so, just click Add Open Source Repo on your Dashboard. No SSH keys or GitHub permissions are involved, since the project is public."

"However, if your Code Climate user is not linked to your GitHub user, you will not be able to see the project's Settings link in our UI. As a result, there are certain administrative actions that you unfortunately will not be able to perform on the project."

http://docs.classic.codeclimate.com/article/291-do-i-have-to-give-you-my-github-permissions
