### ISSUE TITLE
Documentation for rules

### ISSUE THREAD

**Issue by arnar-gunnarsson** [mwielgoszewski/doorman#47]
There doesn't seem to be any documentation regarding the config syntax for rules (on the add > rule page) other than it's expecting a JSON object. I think adding a sample rule to the "rules and alerts" section of the README.md file would go a long way to help people get started using the rules/alerts features of Doorman.

**Comment by mwielgoszewski** [comment]
Thanks for feedback @arnar-gunnarsson. We plan to add documentation soon around rules and alerts; both @andrew-d and I are a bit unhappy with how they're currently implemented, and the UX around it was thrown together on a whim. I'll let @andrew-d comment as to the state of where things are and what the plan is going forward.

**Comment by mwielgoszewski** [comment]
Hey @arnar-gunnarsson, just wanted to provide you with a quick update. We have a PR in the queue, #49 that should make adding/updating rules pretty self explanatory from a UI/UX perspective. No more manually constructing JSON objects. We'd love to get your feedback if you have any.

**Comment by mwielgoszewski** [comment]
@arnar-gunnarsson given the lack of response, I'm going to consider this issue closed.
