### ISSUE TITLE
Handle provision/installation process

### ISSUE THREAD

**Issue by javuto** [mwielgoszewski/doorman#64]
Is there any interest in having a provisioning script, that does all the provisioning of doorman in a given machine? I think it will be beneficial and also providing a dev version inside of a Vagrant box could help too. I can get it done fairly quickly. Kudos for a great project, BTW 👍

**Comment by mwielgoszewski** [comment]
Yes!!!

**Comment by javuto** [comment]
Cool, which system would you like to start supporting? Ubuntu 16.04 LTS sounds ok? The transition to Ubuntu 14.04 LTS should be easy, or the other way around.

**Comment by javuto** [comment]
Starting with Ubuntu 14.04 LTS (trusty64) to avoid a known issue with Ubuntu 16.04 LTS (xenial64) vagrant box: https://github.com/mitchellh/vagrant/issues/7288

**Comment by javuto** [comment]
Would it be useful to have a testing client provisioned at the same time? So with a ```vagrant up``` you would have the server running, and one client VM, already provisioned and enrolled with doorman. We also could make it optional.

**Comment by javuto** [comment]
Implemented in https://github.com/mwielgoszewski/doorman/pull/85
