### ISSUE TITLE
add queries error

### ISSUE THREAD

**Issue by foreversunyao** [mwielgoszewski/doorman#90]
@mwielgoszewski , 
    When I add query , there is error happened(maybe input form has some problems:)

File "/data/doorman-master/doorman/utils.py", line 261, in validate_osquery_query
 
def validate_osquery_query(query):
    # Check if this thread has an instance of the SQLite database
    db = getattr(osquery_mock_db, 'db', None)
    if db is None:
        db = create_mock_db()
        osquery_mock_db.db = db
 
    try:
        db.execute(query)
    except sqlite3.Error:
File "/data/doorman-master/doorman/utils.py", line 253, in create_mock_db
 
def create_mock_db():
    mock_db = sqlite3.connect(':memory:')
    for ddl in schema:
        print ddl
        mock_db.execute(ddl)
    return mock_db
 
 
def validate_osquery_query(query):
    # Check if this thread has an instance of the SQLite database
OperationalError: near "��𐁅񐁔����𠁁񐁌������������������������������������������������������������󠁉񐁔񐁇������������������������": syntax error
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

And input form is  ::

name:processtest
query:select * from processes;
interval:3600
platform:linux
version 1.4.5
description:"test"
value:"test"
query options:log removed(default)
packs:no input
tags:no input

**Comment by mwielgoszewski** [comment]
I am really not sure how you encountered this - I am unable to reproduce it. @andrew-d @dguido have you guys experienced this?

**Comment by foreversunyao** [comment]
@mwielgoszewski 
We found the root cause of this problem, because we use python 2.7, the input date is unicode, and   when we modify code **from mock_db.execute(ddl) to mock_db.execute(ddl.encode())** and the problem is fixed.

Thank you very much.

**Comment by foreversunyao** [comment]
@mwielgoszewski 
    One more question, does these items (Name	Make	Model	Serial	Cpu	Cpu Cores	Memory) of webstie https://xxx:5000/manage/nodes from osqueryd real time collecting by doorman ? or there is another program collecting by osquery log and push them to database, doorman is only a webui ?

    Because after I set up doorman and register node by "ENROLL_SECRET=secret osqueryd --flagfile osquery.flags" ,but https://xxx:5000/manage/nodes webui do not have any data of Name	Make,Model,Serial,Cpu,Cores,Memory.

   If there is any configure about this(eg. ) ,  can you tell more details?
   Thanks.

**Comment by mwielgoszewski** [comment]
@foreversunyao See [`DOORMAN_CAPTURE_NODE_INFO`](https://github.com/mwielgoszewski/doorman#configuration) key in the configuration file for details. You'll need to schedule some queries to actually query that information.

If you create a distributed query, and the state always remains `NEW`, then the nodes the query is intended for are not getting them. What values do you have in your osquery configuration for the following flags?

* `--disable_distributed`
* `--distributed_plugin`
* `--distributed_interval`
* `--distributed_tls_max_attempts`
* `--distributed_tls_read_endpoint`
* `--distributed_tls_write_endpoint`

**Comment by foreversunyao** [comment]
@mwielgoszewski 

I saw DOORMAN_CAPTURE_NODE_INFO this configuration , but I don't know where can I configure this query(select * from system_info;), I tried to configure it at doorman query tab and /etc/osquery/osquery.conf at the node(local server) as below, but they did not work anyway, although osquery log has this message. ? Did I miss some details ? Thanks.
osquery.conf :
{
  "options": {
    "host_identifier": "hostname",
    "schedule_splay_percent": 10
  },
  "schedule": {
    "system_info": {
      "query": "select * from system_info;",
      "interval": 10
    }
  }
}



 osquery flags configuration is as below:

**--pidfile=/tmp/osquery.pid
--host_identifier=uuid
--database_path=/opt/osquery.db
--config_plugin=tls
--config_tls_endpoint=/config
--config_tls_refresh=10
--config_tls_max_attempts=3
--enroll_tls_endpoint=/enroll
--enroll_secret_env=ENROLL_SECRET
--disable_distributed=false
--distributed_plugin=tls
--distributed_interval=10
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/distributed/read
--distributed_tls_write_endpoint=/distributed/write
--logger_plugin=tls
--logger_tls_endpoint=/log
--logger_tls_period=5
--tls_hostname=serverip:5000
--tls_server_certs=./certificate.crt
--log_result_events=false
--pack_delimiter=/
--utc
--verbose
--tls_dump=true**

**Comment by mwielgoszewski** [comment]
@foreversunyao Configure the query on the **queries** page, and then tag the query with a tag that is shared by the nodes you wish to get this information for.

For example, I have a set of queries and packs that I've tagged with `baseline`. All my nodes are also tagged with `baseline`, which results in them receiving in their osquery configuration all the queries, packs, etc associated with the `baseline` tag.

See screenshots below:

On the queries tab:

![image](https://cloud.githubusercontent.com/assets/359029/19644220/93850df0-99bc-11e6-845d-13c55a37baf0.png)

On the packs tab:

![image](https://cloud.githubusercontent.com/assets/359029/19644201/858a49fe-99bc-11e6-94cc-fe634c200f57.png)

On the individual node's page:

![image](https://cloud.githubusercontent.com/assets/359029/19644241/b376d3aa-99bc-11e6-82b7-64d1d590eea1.png)

**Comment by foreversunyao** [comment]
@mwielgoszewski  
   It works , thanks very much for your patient. It's a very nice framework. 
   if convenient we can make a friend, my name is Samuel, my facebook is foreversunyao,I am a SRE and work in Singapore now , we plan to use your platform for our system security monitor.

**Comment by foreversunyao** [comment]
closed.
