### ISSUE TITLE
How to configure doorman to listen on all interfaces?

### ISSUE THREAD

**Issue by ngeorgieff** [mwielgoszewski/doorman#91]
Hello,

Is there an option to configure doorman to listen on all interfaces?
I've  tryied with SERVER_NAME=server.domain.name:5000 but it didn't work with SSL.

I can run it with `python manage.py runserver -h '0.0.0.0' -p 5000` but without SSL.
Please advice.

Thank you,
Nick

**Comment by mwielgoszewski** [comment]
Hi @ngeorgieff, I recommend running nginx as a reverse proxy, bound to an external interface and proxying requests to Doorman running in a wsgi container, which is exposed on a local domain socket or port on localhost.

See the following Flask documentation for more info:

* http://flask.pocoo.org/docs/0.11/deploying/wsgi-standalone/
* http://flask.pocoo.org/docs/0.11/deploying/uwsgi/

**Comment by ngeorgieff** [comment]
Thank you!
